"use strict";

/// AÑADIR LA IMAGEN DE RELLENO EN CASO DE NO HABER IMAGEN BUENA
/// PUEDO SACAR FUERA DE LA FUNCIÓN EL CAMBIO DE CLASE HIGHLIGHT?
/// BOTONES DE RESET DE FAVORITOS, Único y global (Y ACORDARSE DE LLAMAR A LS AL DECLARARLAS)
/// QUE EN NUEVA BŚUQUEDA APAREZCAN RESALTADAS LAS QUE YA ERAN FAVORITAS
